name: Lint the module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # needs: NOTHING
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Pip Update
        run: |
          make -s update-pip
      - name: Lint Dependency Installation
        run: |
          make -s install-lint
      - name: Lint the Project
        run: |
          make -s lint
